//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting.CodeGeneration.TypeScript
{
    public sealed partial class AtsTypeScriptCodeGenerator : Ats.ICodeGenerator
    {
        public string Language { get { throw null; } }

        public System.Collections.Generic.Dictionary<string, string> GenerateDistributedApplication(Ats.AtsContext context) { throw null; }
    }
}